<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-14T21:59:25 IST" name="Suite" finished-at="2023-10-14T21:59:52 IST" duration-ms="26790">
    <groups>
      <group name="Sanity">
        <method signature="LoginTests.login()[pri:1, instance:testScripts.LoginTests@79079097]" name="login" class="testScripts.LoginTests"/>
      </group> <!-- Sanity -->
      <group name="Regression">
        <method signature="LoginTests.login()[pri:1, instance:testScripts.LoginTests@79079097]" name="login" class="testScripts.LoginTests"/>
        <method signature="LoginTests.loginwithWrongCredentails()[pri:2, instance:testScripts.LoginTests@79079097]" name="loginwithWrongCredentails" class="testScripts.LoginTests"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="LoginTests.login()[pri:1, instance:testScripts.LoginTests@79079097]" name="login" class="testScripts.LoginTests"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2023-10-14T21:59:25 IST" name="Test" finished-at="2023-10-14T21:59:52 IST" duration-ms="26790">
      <class name="testScripts.LoginTests">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testScripts.LoginTests@79079097]" started-at="2023-10-14T21:59:26 IST" name="setup" finished-at="2023-10-14T21:59:39 IST" duration-ms="12753" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:1, instance:testScripts.LoginTests@79079097]" started-at="2023-10-14T21:59:39 IST" name="login" finished-at="2023-10-14T21:59:50 IST" duration-ms="10929" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testScripts.LoginTests.login(LoginTests.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="loginwithWrongCredentails()[pri:2, instance:testScripts.LoginTests@79079097]" started-at="2023-10-14T21:59:50 IST" name="loginwithWrongCredentails" finished-at="2023-10-14T21:59:51 IST" duration-ms="430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithWrongCredentails -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testScripts.LoginTests@79079097]" started-at="2023-10-14T21:59:51 IST" name="tearDown" finished-at="2023-10-14T21:59:52 IST" duration-ms="838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testScripts.LoginTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
